### ISSUE TITLE
验证码

### ISSUE THREAD

**Issue by geGDVS** [ZhangChat-Dev-Group/ZhangChat#2]
你这验证码看不清啊
l I | 有啥区别

**Comment by geGDVS** [comment]
还有我一句话都没辩解就给我ban ban ban了
什么玩意

**Comment by MrZhang365** [comment]
你已经严重违规，事实明确，证据充分，所以要ban
验证码不是我写的，是 Dr0 写的，你可以找他。
你要是继续提无理要求，那么后果自负。

**Comment by huolongguo1O** [comment]
另外聊天室内部问题不要到GitHub issue反馈

**Comment by MrZhang365** [comment]
这里只接受代码方面的问题

**Comment by MaggieLOL** [comment]
你可以直接把他从github block了

**Comment by MrZhang365** [comment]
@MaggieLOL 我已经准备了：
[![pCJyrl9.png](https://s1.ax1x.com/2023/06/22/pCJyrl9.png)](https://imgse.com/i/pCJyrl9)

**Comment by geGDVS** [comment]
那我怎么反馈问题

**Comment by MrZhang365** [comment]
我们不需要你反馈的问题，因为你反馈了太多太多无理的要求
